### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by k86td** [stevesloka/validatingwebhook#4]
Hi!

I'm testing some stuff, and I'm aware this repo has not been updated in forever, but still I thought it would be a good step forward to play with dynamic admission controllers.

I'm running into this error:
```
2024/01/11 20:56:14 http2: panic serving 172.18.0.3:15448: runtime error: invalid memory address or nil pointer dereference
goroutine 41 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc0001da018, 0xc0001fdf67, 0xc000001b00)
        /usr/local/go/src/net/http/h2_bundle.go:5706 +0x16b
panic(0xbe41e0, 0x12f55b0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
main.handler(0xdce640, 0xc0001da018, 0xc000238300)
        /webhook/cmd/webhook/main.go:57 +0x210
net/http.HandlerFunc.ServeHTTP(0xd09c50, 0xdce640, 0xc0001da018, 0xc000238300)
        /usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0x1307780, 0xdce640, 0xc0001da018, 0xc000238300)
        /usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc00015e1c0, 0xdce640, 0xc0001da018, 0xc000238300)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.initNPNRequest.ServeHTTP(0xdd0b00, 0xc00003c450, 0xc000055500, 0xc00015e1c0, 0xdce640, 0xc0001da018, 0xc000238300)
        /usr/local/go/src/net/http/server.go:3366 +0x8d
net/http.(*http2serverConn).runHandler(0xc000001b00, 0xc0001da018, 0xc000238300, 0xc0001fe540)
        /usr/local/go/src/net/http/h2_bundle.go:5713 +0x9f
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:5447 +0x4eb
```

I didn't check the code yet. I'm not familiar with Golang, but I could check it when I have time. Just thought I would document the issue here for the time being.

**Comment by k86td** [comment]
For anyone finding this in 3 thousands years. I tested with [kubernetes-validating-webhook](https://github.com/trstringer/kubernetes-validating-webhook) and it worked fine as long as the TLS certificates are valid.
